'Rich PlantUML support for Visual Studio Code. Plugin used with VS Code
'Refer Syntax: https://plantuml.com/sequence-diagram

@startuml my simple order request

actor "Web User" as WebUser
participant "Front End" as Portal
participant Gateway
participant "Identity\nServer" as IdentityServer #yellow
participant "Rest Api" as RestApi
database OrdersDatabase
entity "External\nShipping Service" as ExternalShippingService

autonumber
WebUser -> Portal ++ : Orders Request
group Step: Authentication
    Portal -> Gateway ++: GET /api/v1/orders\nBearer Token
    Gateway -> IdentityServer ++: Authenticate Token
    IdentityServer --> IdentityServer : Validate\nToken
    IdentityServer -[#green]> Gateway : Success, Token Validated
else Authentication Failed
    autonumber 5
    IdentityServer -[#red]> Gateway --: Request Failed
    Gateway -[#red]> Portal : Authentication Failure
    Portal -[#red]> WebUser: Login Again.  
    note right : Authentication has failed  
end

group Call Order API
    autonumber 8.1
    Gateway -> RestApi ++ : GET api/v1/orders
    RestApi --[#blue]> RestApi : Do Some\nProcessing
    group Database Interaction
        RestApi -> OrdersDatabase ++ : Query Orders
        OrdersDatabase -> RestApi -- : Orders
    end
    'loop
    loop Find Shipping status
        autonumber inc
        RestApi -> ExternalShippingService ++ : Find Shipping status
        ExternalShippingService -> RestApi -- : Return Shipping status
    end
    autonumber 10
    RestApi -> Portal --: Orders
end

Portal -> WebUser --: Response

@enduml
